version: '3.8'

services:
  # Raw RAG implementation
  raw-rag-server:
    image: ${DOCKER_USERNAME}/raw-rag-server:latest
    ports:
      - "3000:3000"
    environment:
      - EMBEDDING_SERVER_URL=http://embedding-server:8080
      - CHROMA_URL=http://chroma-db:8000
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - embedding-server
      - chroma-db
      - ollama

  embedding-server:
    image: ${DOCKER_USERNAME}/embedding-server:latest
    ports:
      - "8080:8080"

  # LangChain RAG implementation
  langchain-rag-server:
    image: ${DOCKER_USERNAME}/langchain-rag-server:latest
    ports:
      - "3001:3000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - embedding-server
      - chroma-db
      - ollama

  # Shared services
  chroma-db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G

volumes:
  chroma-data:
  ollama-data:
